Implement model visibility toggling
osrf/traffic_editor pull request #226
Opened 2020-08-31 09:57 UTC by Kevinskwk

This PR adds the feature of hiding & showing the static models on each level in the toggle_floors plugin. Static model names are recorded in the plugin sdf specification and hide/show messages are published on click of the toggle floor button.
![Screenshot from 2020-08-31 17-56-53](https://user-images.githubusercontent.com/50894569/91708097-68e91300-ebb3-11ea-9197-7690270815f6.png)
![Screenshot from 2020-08-31 17-57-01](https://user-images.githubusercontent.com/50894569/91708101-6ab2d680-ebb3-11ea-810b-c5905f42310b.png)

2020-09-01 03:48 UTC, Yadunund requested changes
Thanks for getting this out quickly! The approach is different from the one discussed in #219 but effective nonetheless. Lets reference this method and see what the best approach is. I've left a couple of minor comments for your consideration.

2020-09-01 03:48 UTC, Yadunund commented on building_sim_plugins/building_gazebo_plugins/src/toggle_floors.cpp
> +    for (string model : models)
```suggestion
    for (const string& model : models)
```

2020-09-01 03:48 UTC, Yadunund commented on building_sim_plugins/building_gazebo_plugins/src/toggle_floors.cpp
> +        if (model_ele->GetName() != string("model"))
I think we can get away with checking for this if we change the structure of the loop.
```
auto model_ele = floor_ele->GetElement("model")
while (model_ele)
{
  if (model_ele.HasAttribute("name")
    models.push_back(model_ele->GetAttribute("name")->GetAsString());
  model_ele = model_ele->GetNextElement("model");
}
```

2020-09-01 03:53 UTC, Yadunund commented
Just a thought, should we also toggle visibility of doors on the level?

2020-09-01 09:13 UTC, Kevinskwk commented
I've implemented visibility toggling of doors (normal doors and lift shaft doors) on each level by appending the door model names in the same way. And I think it makes it look a lot better. While I don't think we should do the same to the non-static models. They are also hard to track since they might be moving between different levels.

2020-09-04 07:50 UTC, Kevinskwk commented
I've implemented the toggling of the robot models. The plugin stores the current floor visibilities and robot visibilities and checks if a robot's visibility has changed by checking its current floor in the `RobotState` msg. It's similar to what's done in the `fleet_state_visualizer` and it's slightly laggy due to the `RobotState` msg publishing interval.

I haven't come up with a method to track the current floors of other non-static models (e.g. coke cans in delivery). Any idea on this topic is appreciated.

2020-09-10 09:32 UTC, tanyouliang95 commented
Tested this, and it works as expected! Thanks @Kevinskwk for the awesome work :tada:

2020-09-14 04:52 UTC, Yadunund approved these changes

2020-09-14 04:53 UTC, merged