Implement battery drain and recharge for slotcars
osrf/traffic_editor pull request #242
Opened 2020-10-05 04:12 UTC by mrushyendra

Computes battery drain for each slotcar in each time step and publishes the states of charge on the `/robot_state` topic. Battery drain is computed as a sum of static drain (constant over time) and dynamic drain (due to robot's mass and trajectory), similar to the `simpleDevicePowerSink` and `simpleMotionPowerSink` in `rmf_core`. Also computes recharge if robot is stationary at a charger waypoint.

Adds Ignition and Gazebo classic GUI plugins to enable and disable charge, discharge and instant charge. The GUI plugins publish messages using Ignition/Gazebo transport libraries which are in turn read by the respective Ignition or Gazebo slotcar plugins. I also have a version where they publish messages using ROS2, which is read by the slotcar_common executable at (https://github.com/mrushyendra/traffic_editor/tree/slotcar_charging), if that is preferred instead.

Lastly, the slotcars do not currently stop if the state of charge drops to 0. Should I change the behavior to disable movement if the battery dies?

2020-10-05 04:52 UTC, mrushyendra commented
To test the Ignition GUI plugin, osrf/rmf_demos#144 is required. The `toggle_charging` plugin needs to be selected from the drop down menu on the top right.

![rsz_toggle_charging_ign_gui_plugin](https://user-images.githubusercontent.com/22248849/95041377-1bf3e180-0709-11eb-9e5c-d622f2dc3496.png)

2020-10-08 10:16 UTC, Yadunund requested changes
Thanks for getting this up so quickly! I've left some comments for your consideration. But would like to highlight two glaring issues below.
1. The state of charge `_soc` is stored internally as a percentage while functions `compute_discharge` and `compute_charge` return the fraction of total capacity charged/discharged, ie `dSOC` is a fraction between [0,1]. But in your implementation, you add/subtract this fraction to/from a percentage `_soc`. As a result running the simulation for 5-6hrs only results in <.1% drain in battery. A potential fix for this is to initialize `_soc` to `1.0` along with the same when it charges up. Then we should see more reasonable battery drains. 

2. In the `slotcar_common::update()` method, does the `dist` vector contain  [dx,dy,dyaw] ? From the implementation it looks like it stores [dx,dy,dz]. If this is the case then the values of `v`, `w` and `alpha` will be incorrect. `v` should equal the norm of only the dx/dt and dy/dt components, `w = dyaw/dt` and `alpha = dw/dt`. But right now `v` is the norm dx/dt,dy/dt,dz/dt components while `w=dz/dt` (and hence `alpha` will be incorrect). Let me know if otherwise.

The toggle charger plugin looks good but the placement of the buttons can be lowered a bit as the current layout seems to interfere with the `toggle_floor` plugin button. 
![image](https://user-images.githubusercontent.com/13482049/95445456-a2baef80-0991-11eb-8279-08e4ae53fd97.png)

Could we also set the `mode` field in the `RobotState` message to `MODE_CHARGING` when the battery is being charged. For now let us not render the robot immobile if the battery is fully drained.

2020-10-09 01:44 UTC, mrushyendra commented on building_sim_plugins/building_plugins_common/include/building_sim_common/slotcar_common.hpp
> +            waypoint->GetAttribute("x")->Get(x_val);
Right, I've simplified this bit.

2020-10-09 01:45 UTC, mrushyendra commented on building_sim_plugins/building_plugins_common/src/slotcar_common.cpp
> +    const Eigen::Vector3d dist = compute_dist(_old_pose, _pose);
I somehow overlooked this! Changed it to take into account the difference in yaw angle instead.

2020-10-09 01:47 UTC, mrushyendra commented on building_sim_plugins/building_plugins_common/include/building_sim_common/slotcar_common.hpp
> +  double _soc = 100.0;
Thanks for catching this, changed it [0,1] instead.

2020-10-09 01:49 UTC, mrushyendra commented
Thanks for the comments! I made the necessary changes, including changing the soc range to [0,1] and taking into account dyaw instead of dz when computing the energy loss.

2020-10-09 02:56 UTC, Yadunund commented on building_sim_plugins/building_plugins_common/src/slotcar_common.cpp
> +  robot_state_msg.battery_percent = _soc;
```suggestion
  robot_state_msg.battery_percent = 100 * _soc;
```

2020-10-09 03:00 UTC, Yadunund commented on building_sim_plugins/building_plugins_common/src/slotcar_common.cpp
> +  const double dE = EA + EF;
Can we tidy up this part by renaming `dE2` to dED` for energy drain from devices and adding the same to `dE` in this step.

2020-10-09 07:02 UTC, Yadunund approved these changes
Thanks for addressing all the issues so quickly!

2020-10-12 04:43 UTC, merged